dist: trusty
language: php
php:
  - '5.6'
before_script:
  - composer install
script: 
  - composer --version
  - phpunit --version
  - vendor/bin/phpunit --testdox
deploy:
  provider: heroku
  api_key:
    secure: ""
  app: deceptionpoint
  on:
    repo: Lp063/InstagramPostsReporting